language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "anddopphoopha" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t anddopphoopha/se234-lab10-backend .
- docker push anddopphoopha/se234-lab10-backend
- docker pull anddopphoopha/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cashe:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: Oh1TVtF6XuT84FNgVJrKelrGpVblOOH+UaR90VM/6d/bnuXJAnUizARx1qET9oU+ABU3bVQMFtn6Q6YPF3YvZAKkekyi9/AP3jVRgDtt2gNYuZCrETRUjzoOWsM01nY9rfBgesSA71iOm8mjPXvwf93GkSJN/WPD97QjK/Agxncu2POaVcq29ILLeJdSP+QZcnSP7YFDNMHKTYMXsRTk3JGfJlN2pHI9Q8jsbJ41JrNIdYTN5f920m4qZLfkYX/J0EPRK9J2CawbaWkOTitysytuWqVdLA3w9q051mQp4twr/asc66P2FcEFOm+2f3JmIvS6AdoupaOxKBmwHZnOKPDLNhpR+/tUD3V1fyQLI8mvoTsJ0rHNhU/p1t3jxnZtr99Hfbw3TpnMba+SBzuCijLZ5rtGE9X9iQ4lwLtLZJRnQXYLwgv0uciOqtOlLPkzWbQJPrDlYH5gXRZ30N0cJg25TldgYLKUZOV9t1y6v16XeJuS9WiTRSO1DkMV1420bBq3/oHfJGZ0fBVrjpSDbu1My7NfUPpezhG53nDkdjWKtTndPSM31PMzda6tvBCOFeN5e1CrysubH8FmKQyr0fA4DoHjkIKS8fm1CpUPDjCdMwTWNm/INXC132VDAJG63AVL4xKmewCiqHcrw4XDU5psnraA9Foe03BsRDH8Sxg=
  - secure: j0DJL+PHg8pHP8ohjgtKSHYFaCPgOJ819yWxFDVPCMLjcCFAe+LszCSh7h5810Ux181lIKVw80pDT4oi1r5V0a5CabtEGiE+yjoqC81rVk7iQd9pA3bGNEuOiqnm6sRn6gFa+yCuQBn/YMBOb3+MkoFQXORTY6cnNQ50Yt1iHezPpCl+Ea6yI7ig9uVnQm9A+AIyQiIRSCEzcaEG1DryjwM5uXlB4OO/YOjcOIPT0IMNyYhxFSJqL2emSSw2kzxiwR5MG5d9sM01qOOTS1epv5K+gjxZJ2S4F7sUhFFXd+b1kpytYOzNWaG/N3t7gJX/DzGQtf3bpf/TVaFOttiAJAGO9sOhhkGp6rfABf/O06cVnwM6ImdSM5NMk4bORf6jKSWr3rdZBossQ1VHq1pIzWvsDwgMAntNqrFom4oNcEh40aH8X7oYd3+8DKNNGmuyp2tLDR/TdLtA4BoOTLlp2nMG5dR6OGhprt/6b7GwjwKpc1ExgI0b9jm3AnnF3etEuiLtTVsyMUWATOTBLe/JMZbCCVSGmTlUIbXTcTrBKbWG8iK7+/rsJ291PaS+ms753qG6kBdS7plGHxs9+tidIX/bLFsNffm+q7zsSwYOmkaXsyatWkLJKia32jVH5k7i24RfD7b+JbsTf5lzayobLz48I0UQYdQzH70BuQaLnCI=
  - secure: eN/pCP4IvpxvRn/CbG85sQkg67kpNzyU4Nipq2mSZCZRYpNqjzaUfWxMVT1ouTn3EnpHWXHUdkpzyEhh6OjwkcTKTAi2FlXTSq+RtEqbgrn1rzi0JlyzpsgFpo19rxam3lglUNaK3uJKLgbL49OevnCG8bzQq7zg2RoYXOBkecLmM2OX8foeF++470NpTdceaOgjJTU5EbD7kahbcrEa1WjBgHQvQPg9s/xEXkgXYkE+ZIp9WFnP6pt/VfTtbHMqfUm3pV8pEingHWyuJS0SuFvnh5dVjbc4aN1wp7xMeTfpIsPL3MyuVaG1KaBZJuIuAz+tIR4zddlqZyWKE/Zs6mUsUN/3t/VTFFUi2BqyVRRYj7xZEmBDOle790IipqQy9Fazx38vI3AeyMD+3+zkaFfENZO9a8i3OvIL6Our8hw9kXRdWrx9g9MYggNDcLexpkuoj8dx6S6YrWcPf04biuyoyIuyLU80hBTf4MD5CtvuFZTzHRTyWgwasZL3yOyf+VugmoSzgg5caBIqtkgAROwbyLp2/mqKVq2OQ7zeRCcjYF7/hJF8O6EZQrrb9uiEvBwomdEH0zFl9moKS1M0SBVHah2SnZcxj3SQSX1pmX5Wj4lsQ8ut9kRP6JU7N1P4JPgO0IejyJMo2Hu0zaLQWox4xilRUIQ4GrMvww/flK8=
